messages:
  noPlayer: "§c%player% not found"
  youAreNotPlayer: "§cYou need to be a player to run this command!"
  noArgs: "§cNot enough args"
  kitCreated: "§aKit successfully created!"
  alreadyName: "§cA kit with this name already exists"
customkits:
  pages:
    name: # the name of the page
      icon: OAK_PLANKS # icon of the page
      items: # list of items contained on the page. max 24/page
        - DIAMOND_SWORD
        - NETHERITE_SWORD
guis:
  KitPreviewGUI:
    name: "Kit preview"
    editItemName: "§fEdit kit"
    backItemName: "§fBack"
    displayDefaultItemName: "§fShould the default kit or your customized kit be displayed"
    default: "§6Default"
    customized: "§6Customized"
  KitGUI:
    name: "Kits"
    previousArrow: "§fPrevious page"
    nextArrow: "§fNext page"
    createKitItemName: "§aCreate a new kit"
    iconLore:
      - "§5Left click to load"
      - "§5Right click to preview/edit"
  KitCreateGUI:
    name: "Create kit"
    setNameItemName: "§fClick this to set the name of your kit"
    setIconItemName: "§fClick this to set the icon of your kit"
    setContentItemName: "§fClick this to set the content of your kit"
    saveItemName: "§fClick this to save your kit"
    setNameMessage: "§eType the name of your kit to the chat"
    setIconMessage: "§eHold the item you want as icon and type \"done\""
    setContentMessage: "§eGet your kit into your inventory, then type \"done\""
    nameOrContentNotSet: "§cYou need to set the name and the content of your kit!"
    saved: "§aKit successfully saved!"
    alreadyName: "§cA kit with this name already exists!"
  EditKitGUI:
    name: "Edit kit"
    saveItemName: "§aSave"
    resetItemName: "§4Reset kit"
    backItemName: "§fBack §7(doesn't saves kit)"
    success: "§aKit successfully edited!"
    wrongContents: "§cThere's more or less of something in your kit. Please try again"
    wrongArmor: "§cYou need to have either nothing or the actual armor piece in your armor slots!"
  CustomKitEditorGUI:
    name: "Create a new custom kit"
    pageScrollerBackItemName: "§fBack"
    pageScrollerForwardItemName: "§fForward"
  EditItemGUI:
    name: "Edit item"
    setNameMessage: "§eType the name of the item to chat"
    backItemName: "§fBack"
    enchantsItemName: "§6Enchant"
    nameItemName: "§6Rename"
    trimItemName: "§6Trim"
  EnchantItemGUI:
    name: "Enchant item"
data:
  kits: {}
  customkits: {}