name: KitCats
version: '2.5'
main: hu.jgj52.kitCats.KitCats
api-version: '1.21'
authors: [ JGJ52 ]
depend:
  - LibCats
softdepend:
  - ViaVersion
commands:
  kit:
    permission: kitcats.command.kit
  customkit:
    permission: kitcats.command.customkit
  page:
    permission: kitcats.command.page