name: KitCats
version: '1.5'
main: hu.jgj52.kitCats.KitCats
api-version: '1.21'
authors: [ JGJ52 ]
softdepend:
  - ViaVersion
commands:
  kit:
    permission: kitcats.command.kit
  customkit:
    permission: kitcats.command.customkit
  page:
    permission: kitcats.command.page